// <auto-generated />
using System;
using Anis.SubcategoryFillingMechanism.Commands.Infra.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Anis.SubcategoryFillingMechanism.Commands.Infra.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240708094412_InitailCreate")]
    partial class InitailCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Anis.SubcategoryFillingMechanism.Commands.Domain.Entities.OutboxMessage", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("OutboxMessages");
                });

            modelBuilder.Entity("Anis.SubcategoryFillingMechanism.Commands.Domain.Events.Event", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<Guid>("AggregateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Events");

                    b.HasDiscriminator<string>("Type");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Anis.SubcategoryFillingMechanism.Commands.Domain.Events.SubcategoryFillingMechanismAdded", b =>
                {
                    b.HasBaseType("Anis.SubcategoryFillingMechanism.Commands.Domain.Events.Event");

                    b.Property<string>("Data")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Data");

                    b.HasDiscriminator().HasValue("SubcategoryFillingMechanismAdded");
                });

            modelBuilder.Entity("Anis.SubcategoryFillingMechanism.Commands.Domain.Events.SubcategoryFillingMechanismUpdated", b =>
                {
                    b.HasBaseType("Anis.SubcategoryFillingMechanism.Commands.Domain.Events.Event");

                    b.Property<string>("Data")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Data");

                    b.HasDiscriminator().HasValue("SubcategoryFillingMechanismUpdated");
                });

            modelBuilder.Entity("Anis.SubcategoryFillingMechanism.Commands.Domain.Events.SubcategoryFillingMechanismVideoDeleted", b =>
                {
                    b.HasBaseType("Anis.SubcategoryFillingMechanism.Commands.Domain.Events.Event");

                    b.Property<string>("Data")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Data");

                    b.HasDiscriminator().HasValue("SubcategoryFillingMechanismVideoDeleted");
                });

            modelBuilder.Entity("Anis.SubcategoryFillingMechanism.Commands.Domain.Events.SubcategoryFillingMechanismVideoUpdated", b =>
                {
                    b.HasBaseType("Anis.SubcategoryFillingMechanism.Commands.Domain.Events.Event");

                    b.Property<string>("Data")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Data");

                    b.HasDiscriminator().HasValue("SubcategoryFillingMechanismVideoUpdated");
                });

            modelBuilder.Entity("Anis.SubcategoryFillingMechanism.Commands.Domain.Entities.OutboxMessage", b =>
                {
                    b.HasOne("Anis.SubcategoryFillingMechanism.Commands.Domain.Events.Event", "Event")
                        .WithOne()
                        .HasForeignKey("Anis.SubcategoryFillingMechanism.Commands.Domain.Entities.OutboxMessage", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });
#pragma warning restore 612, 618
        }
    }
}
